title:              "'Tine Zekis"
email:              "tinezekis@gmail.com"
description: >- # this means to ignore newlines until "author:"
  'Tine Zekis (she/her) is a keynote speaker, software engineer, and Imposter
  Syndrome coach. This site contains a collection of content produced by 'Tine.
  Find her blogs, slides, videos, and more.
author:             "'Tine Zekis"
baseurl:            "" # the subpath of your site, e.g. /blog
url:                "https://tinezekis.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Social Profiles
twitter_username:   "tinezekis"
github_username:    "tinezekis"
linkedin_username:  "tinezekis"
medium_username:    "tinezekis"
# facebook_username:  StartBootstrap

# Add your google-analytics ID here to activate google analytics
google_analytics:   "UA-155085823-1"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
